---
audit_header: false
title: Tampa Bay's Best Real Estate Training
description: >-
  Karen & Joe Donovan,  long time Real Estate Brokers in Pinellas County
  Florida, share their own real estate success secrets for free. Joe & Karen
  hope that their Real Estate Tips and  Advice on how they have not only
  survived but thrived in the real estate business for over 25 years will
  inspire and encourage you in your real estate journey!
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Free Strategy Call
    url: /meeting/
  - title: Free Newsletter
    url: /subscribe/
client:
  name: Karen & Joe Donovan
  title:
  license_number:
  about_markdown: >-
    Donovan Home Sales, Inc., founded in 2000, is built on strong core values
    and purpose. We operate in a fun, exciting and challenging environment that
    helps all of us achieve our goals. Each of our staff members and agents are
    dedicated to teamwork, self-improvement, positive attitudes and most
    importantly, a passion and drive to surpass the expectations of every client
    who does business with us. Whether you are looking to sell your home, or
    purchase a new one, we can offer a dedicated professional team and an
    innovative on-line approach.


    Our team of enthusiastic, hard working real estate agents is ready to walk
    you through the process of buying the perfect home or selling your existing
    house at the price you want, with the fewest problems within the time frame
    you want.


    Joe and Karen Donovan, Broker –Owners, have been helping families in the
    Tampa Bay - Pinellas County, St. Pete/Clearwater area for over 25 years. Joe
    & Karen and their team have participated in helping over 1000 families turn
    their real estate dreams and goals into reality.
  market: 'Pinellas County, FL'
  brand: 'Donovan Home Sales, Inc.'
  brokerage:
  address: '801 West Bay Dr. #122<br>Largo, FL 33770'
  phone: 727-595-8880
  phone_type:
  phone2:
  phone2_type:
  email: Karen@homesbydonovan.com
  url: 'http://www.TampabayHomesList.com'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/Tampa-Bay-Real-Estate-Careers-1269603313185548/'
  linkedin_url: 'https://www.linkedin.com/pub/karen-donovan/27/1a9/657'
  gplus_url:
  youtube_url: 'https://www.youtube.com/channel/UCSUrltTypgDYDihP0ox8Obg'
  twitter_url: 'http://www.twitter.com/donovanrealty'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/Karen-Donovan/'
  trulia_url: 'http://www.trulia.com/profile/karen-donovan-agent-11801-230122/overview'
  yelp_url: 'http://www.yelp.com/biz/donovan-home-sales-inc-tampa-bay'
  podcast_url:
podcast:
  title: Tampa Bay Real Estate Podcast with Karen & Joe Donovan
  categories: Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Tampa Bay
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Donovan Home Sales, Inc. - your
    professional Tampa Bay Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Tampa Bay, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Karen & Joe Donovan
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Tampa Bay Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#013e7d'
  theme_color: '#3099c8'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
---